CREATE DATABASE IF NOT EXISTS Actividad3 CHARACTER SET Latin1 COLLATE latin1_spanish_ci;
CREATE TABLE usuarios (id INT NOT NULL AUTO_INCREMENT,usuario VARCHAR(45) NOT NULL,email VARCHAR(45) NOT NULL,password VARCHAR(50) NOT NULL,PRIMARY KEY (id));
